# -*- coding: utf-8 -*-
"""PdSI_T02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vENBN9_38J-oNV2dxqnok1p-8YPbpfiS
"""

# Autor: Daniel Alejandro Martínez Nieto - 222787829
# Procesos de Separación I - Tarea 2

import matplotlib.pyplot as plt
import numpy as np

x_in_ppm = 200.0   # Entrada líquido (Top)
x_out_ppm = 10.0   # Salida líquido (Bottom)
y_in_ppm = 0.0     # Entrada vapor (Bottom) - Vapor puro
L_over_V = 12.0    # Relación L/V
m = 28.0           # Pendiente de equilibrio (Ley de Henry)

y_out_ppm = y_in_ppm + L_over_V * (x_in_ppm - x_out_ppm)

x_max_graph = 220
x_values = np.linspace(0, x_max_graph, 500)

y_eq = m * x_values

y_op = L_over_V * (x_values - x_out_ppm) + y_in_ppm


x_plot = []
y_plot = []

current_x = x_in_ppm
current_y = y_out_ppm

x_plot.append(current_x)
y_plot.append(current_y)

stages = 0
max_stages = 10

while current_x > x_out_ppm and stages < max_stages:
    stages += 1

    next_x = current_y / m

    x_plot.append(next_x)
    y_plot.append(current_y)

    if next_x < x_out_ppm:
        next_y = L_over_V * (next_x - x_out_ppm) + y_in_ppm
    else:
        next_y = L_over_V * (next_x - x_out_ppm) + y_in_ppm

    x_plot.append(next_x)
    y_plot.append(next_y)

    current_x = next_x
    current_y = next_y

plt.figure(figsize=(10, 8))

plt.plot(x_values, y_eq, label=f'Línea de Equilibrio (y={int(m)}x)', color='blue', linewidth=2)
plt.plot(x_values, y_op, label=f'Línea de Operación (L/V={int(L_over_V)})', color='green', linewidth=2, linestyle='--')

plt.plot(x_plot, y_plot, color='black', linewidth=1.5, label='Etapas Teóricas')

plt.scatter([x_in_ppm], [y_out_ppm], color='black', zorder=5)
plt.text(x_in_ppm + 5, y_out_ppm, f'Tope ({int(x_in_ppm)}, {int(y_out_ppm)})', fontsize=9)

plt.scatter([x_out_ppm], [y_in_ppm], color='black', zorder=5)
plt.text(x_out_ppm + 5, y_in_ppm + 100, f'Fondo ({int(x_out_ppm)}, {int(y_in_ppm)})', fontsize=9)

plt.axvline(x=x_out_ppm, color='red', linestyle=':', alpha=0.6, label='Requerimiento (10 ppm)')

plt.title('Diagrama McCabe-Thiele: Desorción de Nitrobenceno', fontsize=14)
plt.xlabel('x ppm (Fase Líquida)', fontsize=12)
plt.ylabel('y ppm (Fase Vapor)', fontsize=12)
plt.xlim(0, x_max_graph)
plt.ylim(0, y_out_ppm * 1.1)
plt.grid(True, which='both', linestyle='--', alpha=0.7)
plt.minorticks_on()
plt.legend()

plt.text(x_max_graph/4, y_out_ppm, f'Número de Etapas Gráficas: {stages}',
         bbox=dict(facecolor='white', alpha=0.8), fontsize=12, color='red')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y_in_ppm = 1200.0   # Entrada gas (Fondo)
x_in_ppm = 0.0      # Entrada líquido (Tope)
removal = 0.97      # 97% remoción

y_out_ppm = y_in_ppm * (1 - removal)
L_V_actual = 200.0  # L/V = 2000/10

x_out_ppm = (1.0 / L_V_actual) * (y_in_ppm - y_out_ppm) + x_in_ppm

m = 169.2

x_max_graph = 9.0
x_values = np.linspace(0, x_max_graph, 100)

y_eq = m * x_values

y_op = L_V_actual * (x_values - x_in_ppm) + y_out_ppm


x_plot = []
y_plot = []

current_x = x_in_ppm
current_y = y_out_ppm # 36 ppm

x_plot.append(current_x)
y_plot.append(current_y)

stages = 0
max_stages = 20

while current_y < y_in_ppm and stages < max_stages:
    stages += 1

    next_x = current_y / m

    x_plot.append(next_x)
    y_plot.append(current_y)

    next_y = L_V_actual * (next_x - x_in_ppm) + y_out_ppm

    if next_y > y_in_ppm:
         pass

    x_plot.append(next_x)
    y_plot.append(next_y)

    current_x = next_x
    current_y = next_y

plt.figure(figsize=(10, 8))

plt.plot(x_values, y_eq, label=f'Equilibrio (y={m}x)', color='blue')
plt.plot(x_values, y_op, label=f'Operación (L/V={L_V_actual})', color='green', linestyle='--')
plt.plot(x_plot, y_plot, color='black', linewidth=1.5, label='Etapas Teóricas')

plt.scatter([x_in_ppm], [y_out_ppm], color='black', zorder=5) # Tope
plt.text(x_in_ppm + 0.2, y_out_ppm + 50, 'Tope (Salida Gas)', fontsize=9)

plt.scatter([x_out_ppm], [y_in_ppm], color='black', zorder=5) # Fondo
plt.text(x_out_ppm - 1.5, y_in_ppm, 'Fondo (Entrada Gas)', fontsize=9)

plt.title('Diagrama McCabe-Thiele: Absorción de H2S', fontsize=14)
plt.xlabel('x ppm (Fase Líquida)', fontsize=12)
plt.ylabel('y ppm (Fase Gas)', fontsize=12)
plt.xlim(0, x_max_graph)
plt.ylim(0, y_in_ppm * 1.1)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()

plt.tight_layout()
plt.show()